name: Push

on:
  push:
    branches:
      - 'main'

jobs:
  push:
    uses: stakater/.github/.github/workflows/push_container.yaml@v0.0.35
    with:
      DOCKER_FILE_PATH: Dockerfile
      RELEASE_BRANCH: main
    secrets:
      CONTAINER_REGISTRY_URL: ${{ secrets.STAKATER_NEXUS_PREPROD_REGISTRY }}/stakater
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.STAKATER_NEXUS_PREPROD_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.STAKATER_NEXUS_PREPROD_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
      GH_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
